blank_issues_enabled: true
contact_links:
  - name: Поддержать проект
    url: https://github.com/AndyShaman/BYDMate/blob/main/SUPPORT.md
    about: Реквизиты для донатов в USDT (сети EVM: Arbitrum, Optimism, Polygon, BNB, Avalanche, Ethereum)
