package com.bydmate.app.voice

enum class ActionSlot { OPEN, CLOSE, ON, OFF, SET, VENT, HEAT_1, HEAT_2, HEAT_3, VENT_1, VENT_2, VENT_3, WARMER, COOLER, HALF, LOUDER, QUIETER }

enum class DeviceSlot {
    WINDOW_ALL, WINDOW_FRONT, WINDOW_REAR,
    WINDOW_DRIVER, WINDOW_PASSENGER, WINDOW_REAR_LEFT, WINDOW_REAR_RIGHT,
    AC_AUTO, AC_FLOW, AC_TEMP, AC_RECIRC_INNER, AC_RECIRC_OUTER, DEFROST_FRONT,
    SEAT_DRIVER_HEAT, SEAT_PASSENGER_HEAT, SEAT_DRIVER_VENT, SEAT_PASSENGER_VENT,
    MIRROR_HEAT, LIGHT_AMBIENT, LIGHT_DRL, LIGHT_INTERIOR,
    LOCK, CAR, SUNROOF, SUNSHADE, TRUNK, VOLUME,
}

data class ValueSpec(val min: Int, val max: Int)
