#!/usr/bin/env python3
# Generate an on-device sh snapshot script from fid-candidates.yaml.
# The output is a self-contained shell script that loops N times calling
# `service call autoservice <tx> i32 <dev> i32 <fid>` per yaml entry,
# writing raw outputs to /sdcard/Download/native-stack/work-<state>/snap-<i>/.
# Used for drive/charge/sleep states where the Mac loses WiFi to the DiLink.
#
# Usage: gen-on-device-snap.py --yaml PATH --state s3 --count 5 --interval 2

import argparse, sys, yaml

ALLOWED_TX = {5, 7}  # tx=6 (setInt) FORBIDDEN in Phase 1.

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--yaml", required=True)
    ap.add_argument("--state", required=True)
    ap.add_argument("--count", type=int, default=5)
    ap.add_argument("--interval", type=int, default=2)
    args = ap.parse_args()

    entries = yaml.safe_load(open(args.yaml))
    valid = []
    for e in entries:
        if not e.get("fid") or not e.get("device") or not e.get("transact"):
            continue
        tx = int(e["transact"])
        if tx not in ALLOWED_TX:
            print(f"# SKIPPED {e['param']}: forbidden tx={tx}", file=sys.stderr)
            continue
        valid.append((e["param"], tx, int(e["device"]), int(e["fid"])))

    print(f"# {len(valid)} fids will be snapped per iteration", file=sys.stderr)

    print(f"""#!/system/bin/sh
# Auto-generated by gen-on-device-snap.py for state={args.state}.
# count={args.count} interval={args.interval}s
# {len(valid)} params, transact 5/7 only (read-only).
set -u
STATE="{args.state}"
COUNT={args.count}
INTERVAL={args.interval}
BASE=/sdcard/Download/native-stack
WORK="$BASE/work-${{STATE}}"
mkdir -p "$WORK"
echo "[runner] start state=$STATE count=$COUNT interval=$INTERVAL ts=$(date -u +%s)" > "$WORK/runner.log"

i=1
while [ $i -le $COUNT ]; do
  SDIR="$WORK/snap-${{i}}"
  mkdir -p "$SDIR"
  date -u +%s > "$SDIR/ts.txt"
  echo "[runner] snap $i ts=$(cat "$SDIR/ts.txt")" >> "$WORK/runner.log"
""")

    for param, tx, dev, fid in valid:
        # Each line: 4 args to `service call autoservice`. Rate-limit between calls.
        print(f'  service call autoservice {tx} i32 {dev} i32 {fid} > "$SDIR/native-{param}.raw" 2>&1')
        print('  sleep 0.25')

    print(f"""  if [ $i -lt $COUNT ]; then
    sleep $INTERVAL
  fi
  i=$((i+1))
done

echo "[runner] done ts=$(date -u +%s)" >> "$WORK/runner.log"
touch "$WORK/.done"
""")

if __name__ == "__main__":
    main()
